sudo: true

language: node_js

node_js:
  - "8"
branches:
  only:
    - master

addons:
  apt:
    packages:
      - oracle-java9-installer
      - oracle-java9-set-default

# We'll manually install versions of ES ourselves
# services:
#   - elasticsearch

script: npm run test

env:
  matrix:
    - "ES_VERSION=1.5.0 ES_DOWNLOAD_URL=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz"
    - "ES_VERSION=2.3.4 ES_DOWNLOAD_URL=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz"
    - "ES_VERSION=5.6.4 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz"
    - "ES_VERSION=6.0.0 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz"
    - "ES_VERSION=7.0.0-beta1 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}-linux-x86_64.tar.gz"

before_install:
  ## ES has different download locations for each version, so we'll download them both and then just use the one we want
  - curl -Lo elasticsearch.tar.gz ${ES_DOWNLOAD_URL}
  ## Now, use the ENV to choose the version
  - tar -xzf elasticsearch.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
  # ES needs some time to start
  - wget -q --waitretry=1 --retry-connrefused -T 15 -O - http://127.0.0.1:9200
